version: '3.5'
services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: laravel_ddd_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-ddd-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_ddd_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
      - "4443:4443"
    volumes:
      - ../:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-ddd-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: laravel_ddd_db
    restart: unless-stopped
    tty: true
    ports:
      - "8806:8806"
    environment:
      MYSQL_DATABASE: laravel_sample
      MYSQL_ROOT_PASSWORD:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-ddd-network

#Docker Networks
networks:
  laravel-ddd-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local